### ISSUE TITLE
JsonConvert error using jsonx 2.0.2

### ISSUE THREAD

**Issue by flaviosuardi** [IdanAizikNissim/Cosmic#4]
Hi,

I have an issue in a Flutter app.  When I try to lauch my app I have this error message:

`compiler message: file:///Users/flaviosuardi/Library/flutter/.pub-cache/hosted/pub.dartlang.org/jsonx-2.0.2/lib/jsonx.dart:231:22: Error: A value of type '(dart.core::String) → dart.core::DateTime' can't be assigned to a variable of type '(dynamic) → dynamic'.
compiler message: Try changing the type of the left hand side, or casting the right hand side to '(dynamic) → dynamic'.
compiler message:   DateTime: DateTime.parse
compiler message:                      ^
compiler message: file:///Users/flaviosuardi/Library/flutter/.pub-cache/hosted/pub.dartlang.org/jsonx-2.0.2/lib/jsonx.dart:435:37: Error: The getter 'type' isn't defined for the class 'dart.mirrors::DeclarationMirror'.
compiler message: Try correcting the name to the name of an existing getter, or defining a getter or field named 'type'.
compiler message:           r[k] = new _Property(k, v.type, v.metadata);
compiler message:                                     ^
compiler message: file:///Users/flaviosuardi/Library/flutter/.pub-cache/hosted/pub.dartlang.org/jsonx-2.0.2/lib/jsonx.dart:437:37: Error: The getter 'returnType' isn't defined for the class 'dart.mirrors::DeclarationMirror'.
compiler message: Try correcting the name to the name of an existing getter, or defining a getter or field named 'returnType'.
compiler message:           r[k] = new _Property(k, v.returnType, v.metadata);
compiler message:                                     ^
Compiler failed on /Users/flaviosuardi/Documents/Tiknil/App/Flutter/calcetto/lib/main.dart
`

In my project I have define the client like this:
`@Client(
    path: "https://dev.intercheckws.it",
    converter: const JsonConverter()
)`

and I used `cosmic:generate` in order to generate the api implementation without any problems.

Is it an issue due to Flutter framework because `dart:mirror` is missing? Or am I missing something?

Thanks.

**Comment by IdanAizikNissim** [comment]
You did good generating the client,
But the JsonConverter in the lib is using jsonx which use  dart:mirror,
It's pretty misleading sorry about that.
The way to go parsing json to dart object is by using package:json_annotation in order to generate json map to object and connect it to cosmic converter.
Great sources about json_annotation:
https://flutter.io/json/
http://aloisdeniel.github.io/flutter-json-serialization/ 

I will also upload an example flutter project using cosmic+json_annotation shortly

Sorry about the late response.

**Comment by IdanAizikNissim** [comment]
checkout [https://github.com/IdanAizikNissim/RifRoof](RifRoof) repo.
you will find _clients/giphy_client.dart_ using **GiphyConverter** which is a _cosmic.Converter_
"proxing" the decode and encode functions to a Gif object generated by _json_annotation_
in order to parse the json map to object and vice versa
